### ISSUE TITLE
Untrusted

### ISSUE THREAD

**Issue by Panchii116** [ChoZenTime/aristois-pasted-by-choZen#3]
Hi, I took your source, removed a lot of features, just left aimbot, some misc, bhop and visuals and I inject using KateBot settings (manual map, extreme scrambling, no new entrypoint, hide module, erase pe, silent inject, close after inject) and i get a untrusted ban in 30-120 mins. Any idea what might be cause?

**Comment by designer1337** [comment]
extreme injector, lol.

**Comment by Panchii116** [comment]
@designer1337 well what do you suggest besides writing my own

**Comment by CroutonSilent** [comment]
> @designer1337 well what do you suggest besides writing my own

literally any other injector

**Comment by Telepracity** [comment]
> @designer1337 well what do you suggest besides writing my own

RandoInjector

**Comment by ChoZenTime** [comment]
RandoInjector is the best for beginner
